### ISSUE TITLE
bugs exist in OAuth2Method?

### ISSUE THREAD

**Issue by wfwei** [askedrelic/libgreader#11]
auth.py has compile error, I change it to :
`
...
def post(self, url, postParameters=None, urlParameters={}):
       ...
        getString = self.getParameters(urlParameters)
        request = urllib2.Request(url + '?' + getString)
'#'        below is original one
'#'        request = urllib2.Request(url + '?' + self.getParameters(parameters))
        postString = self.postParameters(postParameters)
        ...
`
It's a pitty, this still can not work...
Can you help me out this problem?

**Comment by askedrelic** [comment]
Thanks for creating this issue! You are correct, I merged in OAuth2 support and did not fully test POST functionality.

This is now fixed in 89a5a9c, with a test. I will release v0.6.2 with this fix once I get some sleep!
