### ISSUE TITLE
Callback url with parameters

### ISSUE THREAD

**Issue by pigmej** [askedrelic/libgreader#2]
you cannot use callback url like:
http://localhost/something?test=test&foo=bar

if you do it. you will be redirected to:
http://localhost/something?test=test

**Comment by askedrelic** [comment]
I have verified this; only the first key/value arg gets returned on the callback.

However, not sure if this is something on the library side I can control. The callback url that is passed to Google contains multiple args, but Google isn't passing them back. This is happening during the OAuth step that isn't specific to Google Reader, perhaps Google has better docs on this limitation.
