### ISSUE TITLE
Oath2 test 

### ISSUE THREAD

**Issue by kousha789123** [askedrelic/libgreader#5]
I cannot make use of Oath2, I don't know why. test shows also...

```
ERROR: test_full_auth_and_access_userdata (__main__.TestOAuth2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_auth.py", line 150, in test_full_auth_and_access_userdata
    auth.setAccessToken()
  File "build/bdist.linux-x86_64/egg/libgreader/auth.py", line 297, in setAccessToken
    raise IOError('Error getting Access Token')
IOError: Error getting Access Token
```

**Comment by kousha789123** [comment]
Well, I have it working in my application; there is a problem with the way automated "automated_oauth2_approval" works I guess.

Great api :) btw.

**Comment by askedrelic** [comment]
Hmm, automated_oauth2_approval is an automated way to load the "approve this oauth application" using mechanize and approval the app to get an access token. I have seen before Google figure out that you are trying to "approve" an app automatically and block you as being a spam bot. If you can't that function to work, just print out the url, visit it yourself, and copy out the access token, I detailed a similar process in this blog post: http://asktherelic.com/2010/04/26/accessing-google-reader-via-oauth-and-python/

Again, glad you figured things, sorry it wasn't easier!

**Comment by kousha789123** [comment]
It would be nice if you could include the commands to authenticate from Oauth2 like you have done it with oauth. because the commands are not the same and the flow is different. I had to read the code to figure it out whereas for oauth it was easy following the usage file.
